name: Optimizely Experiment Pipeline

on:
  push:
    branches: [ main, optimizely-pipeline ]

jobs:
  apply-experiments:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: cd .ci-scripts/optimizely-pipeline && npm ci
    - name: Apply Experiments
      run: cd .ci-scripts/optimizely-pipeline && npm start
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: yarn install
    - name: Build site
      run: yarn build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy site to S3 bucket
      run: aws s3 sync ./build/ s3://experiment-pipeline-demo --delete